### ISSUE TITLE
Why function and not arrows

### ISSUE THREAD

**Issue by Alireza29675** [thatrealdann/login-page#1]
Due to your question, we can only use "function"s here and the reason comes from those "this" keywords we're using inside the function.
This article may help you about why you get some errors when you change this file's "function"s to "arrow function"s:
https://dmitripavlutin.com/when-not-to-use-arrow-functions-in-javascript/

`app/models/user.js`:
```javascript
// ** generating a hash **
userSchema.methods.generateHash = function(password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

// ** checking if password is valid **
userSchema.methods.validPassword = function(password) {
    return bcrypt.compareSync(password, this.local.password);
};
```

**Comment by urgeekneighbor** [comment]
How can I ever thank you enough ¯\_(ツ)_/¯
